"""Chat pipeline compatibility shim.

Implementation moved to backend.teach (teaching windows),
backend.attachments (hints/maps/history scans) and backend.flow
(turn orchestration: run_chat/regenerate_chat). Import from those
modules in new code; this module re-exports everything.
"""

from backend.teach import (TEACHING_WINDOW_SLIDES, TEACHING_WINDOW_CHARS, TEACHING_INLINE_MAX_BYTES, TEACHING_CONTINUATION_MAX_CHARS, _TEACHING_FILE_RE_NEW, _TEACHING_FILE_RE, _match_teaching_header, _TEACHING_SLIDE_MARK_RE, _TEACHING_ADMIN_SIGNALS, _TEACHING_COURSE_CODE_RE, _TEACHING_CONCEPT_SIGNALS, _TEACHING_TEACH_VERBS, _TEACHING_SUBJECT_NOUNS, _TEACHING_PACE_SLOW, _TEACHING_PACE_FAST, _TEACHING_RUSH_SIGNALS, _TEACHING_DEEP_SIGNALS, TEACHING_SUFFIX, _teaching_scope_line, _is_teaching_request, _is_admin_block, _last_teaching_state, _last_teaching_ends_with_recall, _is_recall_answer, _pace_direction, _time_pressure, _is_pace_feedback, _is_teaching_continuation, _extract_teaching_blocks, _extract_pptx_blocks, _extract_pdf_blocks, _split_marked_blocks, _select_teaching_window, _teaching_window_hint, _TEACHING_SCOPE_RE, _TEACHING_CITE_RE, _TEACHING_CITE_RANGE_RE, _TEACHING_CONCEPT_RE, _TEACHING_RECALL_RE, _TEACHING_BANNED_FOOTER_RE, _TEACHING_FABRICATION_RES, TEACHING_REPAIR_TIMEOUT_SECONDS, _teaching_scope_from_send, _validate_teaching_draft, _repair_teaching_draft, _maybe_repair_teaching_turn, _TEACHING_SECTION_RES, _TEACHING_IMPORTANCE_RE, _classify_recall_type, _log_teaching_format)  # noqa: F401
from backend.attachments import (_escape_hint, attachment_hint, _ATTACH_TEXT_CACHE, _ATTACH_TEXT_LOCK, _ATTACH_TEXT_MAX, _attachment_text_hint, attachments_overview, _UPLOAD_MAP_CACHE, _UPLOAD_MAP_LOCK, _upload_map, _resolve_attachments, _iter_recent_valid_uploads, _recent_image_ids, _recent_document_attachments)  # noqa: F401
from backend.flow import (build_chat_history, _assistant_meta, _fallback_info, _clean_sources, _available_for_gate, _attachment_classifier, _check_limits, _load_state, _complete_turn, _memory_and_project, _apply_teaching_session, _apply_attachment_gate, run_chat, _turn_approvals, _complete_turn_guarded, regenerate_chat, EPISODIC_MIN_MESSAGES, EPISODIC_SUMMARY_CHARS, maybe_attach_episodic_summary, archive_current)  # noqa: F401

__all__ = [
    "TEACHING_WINDOW_SLIDES",
    "TEACHING_WINDOW_CHARS",
    "TEACHING_INLINE_MAX_BYTES",
    "TEACHING_CONTINUATION_MAX_CHARS",
    "_TEACHING_FILE_RE_NEW",
    "_TEACHING_FILE_RE",
    "_match_teaching_header",
    "_TEACHING_SLIDE_MARK_RE",
    "_TEACHING_ADMIN_SIGNALS",
    "_TEACHING_COURSE_CODE_RE",
    "_TEACHING_CONCEPT_SIGNALS",
    "_TEACHING_TEACH_VERBS",
    "_TEACHING_SUBJECT_NOUNS",
    "_TEACHING_PACE_SLOW",
    "_TEACHING_PACE_FAST",
    "_TEACHING_RUSH_SIGNALS",
    "_TEACHING_DEEP_SIGNALS",
    "TEACHING_SUFFIX",
    "_teaching_scope_line",
    "_is_teaching_request",
    "_is_admin_block",
    "_last_teaching_state",
    "_last_teaching_ends_with_recall",
    "_is_recall_answer",
    "_pace_direction",
    "_time_pressure",
    "_is_pace_feedback",
    "_is_teaching_continuation",
    "_extract_teaching_blocks",
    "_extract_pptx_blocks",
    "_extract_pdf_blocks",
    "_split_marked_blocks",
    "_select_teaching_window",
    "_teaching_window_hint",
    "_TEACHING_SCOPE_RE",
    "_TEACHING_CITE_RE",
    "_TEACHING_CITE_RANGE_RE",
    "_TEACHING_CONCEPT_RE",
    "_TEACHING_RECALL_RE",
    "_TEACHING_BANNED_FOOTER_RE",
    "_TEACHING_FABRICATION_RES",
    "TEACHING_REPAIR_TIMEOUT_SECONDS",
    "_teaching_scope_from_send",
    "_validate_teaching_draft",
    "_repair_teaching_draft",
    "_maybe_repair_teaching_turn",
    "_TEACHING_SECTION_RES",
    "_TEACHING_IMPORTANCE_RE",
    "_classify_recall_type",
    "_log_teaching_format",
    "_escape_hint",
    "attachment_hint",
    "_ATTACH_TEXT_CACHE",
    "_ATTACH_TEXT_LOCK",
    "_ATTACH_TEXT_MAX",
    "_attachment_text_hint",
    "attachments_overview",
    "_UPLOAD_MAP_CACHE",
    "_UPLOAD_MAP_LOCK",
    "_upload_map",
    "_resolve_attachments",
    "_iter_recent_valid_uploads",
    "_recent_image_ids",
    "_recent_document_attachments",
    "build_chat_history",
    "_assistant_meta",
    "_fallback_info",
    "_clean_sources",
    "_available_for_gate",
    "_attachment_classifier",
    "_check_limits",
    "_load_state",
    "_complete_turn",
    "_memory_and_project",
    "_apply_teaching_session",
    "_apply_attachment_gate",
    "run_chat",
    "_turn_approvals",
    "_complete_turn_guarded",
    "regenerate_chat",
    "EPISODIC_MIN_MESSAGES",
    "EPISODIC_SUMMARY_CHARS",
    "maybe_attach_episodic_summary",
    "archive_current",
]
