"""OLE garbage filtering: embedded-binary junk must not bury real text.

Regression for a 5MB legacy .ppt of photographed lecture slides whose
extraction came out as pure Photoshop EXIF/XMP + JPEG entropy (13.5k
chars, zero lecture keywords) because junk sorts before real text in
byte order and exhausted the output cap. Synthetic blobs only — no user
data. No network, no quota.
"""

import os
import sys

import pytest

sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

from tools.document_tool import _is_ole_garbage, _ole_strings_text

LECTURE_SENTENCE = (
    "A circuit that visits each vertex of the graph once and only once "
    "must return to the starting vertex when the tour is complete."
)
XMP_JUNK = (
    "<x:xmpmeta xmlns:x='adobe:ns:meta/' x:xmptk='XMP toolkit 3.0-28'>"
    "<rdf:Description rdf:about='uuid:496a1a66' "
    "xmlns:exif='http://ns.adobe.com/exif/1.0/'>"
    "<exif:PixelXDimension>221</exif:PixelXDimension>"
    "<photoshop:History></photoshop:History>"
    "Adobe Photoshop CS Windows 2006:10:08 8BIM boundsObjc"
)
QUANT_TABLE = "%&'()*456789:CDEFGHIJSTUVWXYZcdefghijstuvwxyz"


def _blob(*texts):
    return b"\x00\x00".join(t.encode("ascii") for t in texts)


def _binary_split_blob(*tokens):
    # Real OLE dumps intersperse binary bytes between short fragments;
    # model that with \x01 separators so each token is judged alone.
    return b"\x01".join(t.encode("ascii") for t in tokens)


def test_xmp_and_photoshop_markers_dropped_strict():
    assert _is_ole_garbage(XMP_JUNK, strict=True) is True
    assert _is_ole_garbage("Adobe Photoshop CS Windows", strict=True) is True
    assert _is_ole_garbage("8BIM slice data here", strict=True) is True


def test_jpeg_entropy_and_slice_ids_dropped_strict():
    for token in ("7GWgw", "AQaq", "dEU6te", "s=*}z", "~kRRs", "v-osr",
                  "CN5Tc", "mcgfEL", "wr 90", "autoGenerated",
                  "boundsObjc", "Top long", "cellTextIsHTMLbool"):
        assert _is_ole_garbage(token, strict=True) is True, token


def test_quant_table_runs_dropped_both_modes():
    assert _is_ole_garbage(QUANT_TABLE, strict=True) is True
    assert _is_ole_garbage(QUANT_TABLE, strict=False) is True


def test_real_prose_kept_strict():
    assert _is_ole_garbage(LECTURE_SENTENCE, strict=True) is False
    assert _is_ole_garbage("Traveling salesman problem", strict=True) is False
    assert _is_ole_garbage("Given -> Formula -> Solve -> Answer", strict=True) is False
    assert _is_ole_garbage("A* search expands the best node", strict=True) is False


def test_lenient_doc_keeps_short_headings():
    # Legacy .doc behavior preserved: single-word headings survive.
    assert _is_ole_garbage("Introduction", strict=False) is False
    assert _is_ole_garbage("Introduction", strict=True) is True


def test_junk_first_ordering_keeps_real_text():
    blob = _blob(XMP_JUNK, QUANT_TABLE,
                 LECTURE_SENTENCE,
                 "The Traveling Salesman Problem asks for the shortest tour.")
    blob += _binary_split_blob("7GWgw", "AQaq", "dEU6te", "s=*}z",
                               "boundsObjc", "autoGenerated")
    out = _ole_strings_text(blob, ".ppt")
    assert "vertex of the graph" in out
    assert "Traveling Salesman Problem" in out
    assert "xmpmeta" not in out.lower()
    assert "photoshop" not in out.lower()
    assert "cdefghijstuvwxyz" not in out
    assert "autoGenerated" not in out
    assert "legacy .ppt extracted" in out


def test_garbage_only_raises_not_empty():
    blob = _blob(XMP_JUNK)
    blob += _binary_split_blob("7GWgw", "AQaq", "~kRRs")
    with pytest.raises(ValueError, match="no extractable text"):
        _ole_strings_text(blob, ".ppt")


def test_never_raises_on_binary():
    assert _is_ole_garbage("", strict=True) is True
    assert _is_ole_garbage("ok", strict=True) is True
