"""Per-user persistent storage (chats, notes, structured memory).

Package split of the former `services/storage.py` monolith — one
submodule per concern (`ids`, `paths`, `io`, `cleaners`, `store`).
Every name the old module exposed is re-exported here, so
`from services.storage import X` keeps working unchanged.
"""

from services.storage.cleaners import (
    _clean_artifact,
    _clean_attachment,
    _clean_brief_record,
    _clean_chat_record,
    _clean_project_record,
    _clean_tool_names,
    _clean_workflow_record,
    _clean_workflow_step,
    clean_generation_spec,
    clean_messages,
    clean_source_record,
)
from services.storage.ids import (
    _ID16_RE,
    _SOURCE_URL_SCHEMES,
    _SPEC_TOOLS,
    ATTACH_KINDS,
    MAX_MODEL_NAME_LEN,
    MAX_MSGS_PER_CHAT,
    MAX_PROJECT_NAME_LEN,
    MAX_SOURCES,
    MAX_SOURCE_DOMAIN_LEN,
    MAX_SOURCE_TITLE_LEN,
    MAX_SOURCE_URL_LEN,
    MAX_STORED_CHATS,
    MAX_TOOL_NAME_LEN,
    MAX_TOOL_NAMES,
    PROJECTS_VERSION,
    RESPONSE_MODES,
    StorageError,
    WorkflowNotFoundError,
    is_valid_id,
    new_conversation_id,
)
from services.storage.io import (
    _LOCKS_MAX,
    _acquire_interprocess,
    _lock_dir_for,
    _locks,
    _locks_guard,
    _read_json,
    _release_interprocess,
    _thread_depth,
    _tmp_path,
    _write_json,
    atomic_replace,
    path_lock,
)
from services.storage.paths import data_root, sanitize_user_key, user_dir
from services.storage.store import UserStore

__all__ = [
    "ATTACH_KINDS",
    "MAX_MODEL_NAME_LEN",
    "MAX_MSGS_PER_CHAT",
    "MAX_PROJECT_NAME_LEN",
    "MAX_SOURCE_DOMAIN_LEN",
    "MAX_SOURCE_TITLE_LEN",
    "MAX_SOURCE_URL_LEN",
    "MAX_SOURCES",
    "MAX_STORED_CHATS",
    "MAX_TOOL_NAME_LEN",
    "MAX_TOOL_NAMES",
    "PROJECTS_VERSION",
    "RESPONSE_MODES",
    "StorageError",
    "UserStore",
    "WorkflowNotFoundError",
    "_ID16_RE",
    "_LOCKS_MAX",
    "_SOURCE_URL_SCHEMES",
    "_SPEC_TOOLS",
    "_acquire_interprocess",
    "_clean_artifact",
    "_clean_attachment",
    "_clean_brief_record",
    "_clean_chat_record",
    "_clean_project_record",
    "_clean_tool_names",
    "_clean_workflow_record",
    "_clean_workflow_step",
    "_lock_dir_for",
    "_locks",
    "_locks_guard",
    "_read_json",
    "_release_interprocess",
    "_thread_depth",
    "_tmp_path",
    "_write_json",
    "atomic_replace",
    "clean_generation_spec",
    "clean_messages",
    "clean_source_record",
    "data_root",
    "find_chat_by_id",
    "is_valid_id",
    "new_conversation_id",
    "path_lock",
    "sanitize_user_key",
    "user_dir",
]
