"""Shared junk filter for legacy-OLE strings extraction (.doc/.ppt/.xls).

Embedded pictures inside legacy Office binaries surface printable
strings (EXIF/XMP metadata, JPEG entropy, quant tables, slice
identifiers) BEFORE real document text in byte order — on one 5MB
photographed-slides .ppt the unfiltered dump was pure Photoshop
metadata and the output cap filled before any lecture text. These
helpers identify binary-origin strings; they never match genuine
prose. Used by tools/document_tool.py (read path) and services/kb.py
(KB ingest + teaching fallback). Zero dependencies beyond stdlib.
"""

from __future__ import annotations

import logging
import re

logger = logging.getLogger(__name__)

# Markers of embedded-binary metadata (EXIF/XMP/JPEG headers from pictures
# inside legacy Office files). Never user content — always safe to drop.
OLE_METADATA_MARKERS = frozenset({
    "adobe", "xmp", "photoshop", "8bim", "exif", "jfif", "icc_profile",
    "xmlns", "rdf:", "xpacket", "tiff:", "dc:",
    # OOXML-internal part paths sometimes embedded in legacy binaries
    # (never slide content, which lives in slide*.xml).
    "slidemaster", "slidelayout", "theme/", "drs/", "_rels", ".rels",
})

# Characters that appear in genuine prose (plus URL/path punctuation,
# slide arrows "->" and terms like "A*"). JPEG entropy garbage
# ("s=*}z ~kRRs") far exceeds this alphabet.
OLE_PROSE_EXTRA = frozenset(" .,;:()\"'!?/->*")

# JPEG quantization/Huffman tables surface as monotonic runs
# ("cdefghijstuvwxyz", "456789", "STUVWX") — never present in genuine
# prose (years, versions, and page numbers are all shorter).
SEQ_RUN_LEN = 6
_LOWER_WORD_RE = re.compile(r"[a-z]{4,}")


def has_seq_run(text: str, run_len: int = SEQ_RUN_LEN) -> bool:
    """True when text holds run_len+ consecutive codepoints (either direction)."""
    try:
        current, best = 1, 1
        prev = None
        for ch in text.lower():
            code = ord(ch)
            if prev is not None and abs(code - prev) == 1:
                current += 1
                best = max(best, current)
                if best >= run_len:
                    return True
            else:
                current = 1
            prev = code
        return False
    except Exception:
        return False


def is_ole_garbage(text: str, strict: bool = False) -> bool:
    """True for embedded-binary/metadata strings, never real prose (never raises).

    Args:
        text: One candidate string from the binary dump.
        strict: Extra shape rules for image-heavy .ppt binaries (short
            entropy fragments, table identifiers, quant-table runs) that
            would wrongly drop real single-word headings in .doc/.xls.
    """
    try:
        low = text.lower()
        if ("<" in text and ">" in text) or "?>" in text:
            return True  # XML/XMP/RDF/HTML fragments from embedded objects
        if any(m in low for m in OLE_METADATA_MARKERS):
            return True
        if not text:
            return True
        if has_seq_run(text):
            return True  # JPEG quant/Huffman table runs, never prose
        if len(text) < 30:
            if not strict:
                # Lenient (.doc/.xls): legacy behavior — keep short real
                # lines (including single-word headings); only the
                # metadata/XML/sequence rules above apply.
                return False
            # Image-heavy .ppt binaries: short fragments are entropy pairs
            # ("wr 90"), slice identifiers ("autoGenerated") far more often
            # than real bullets. Keep only space-separated, prose-shaped
            # phrases of substance; lone titles are indistinguishable
            # from identifier noise at this fidelity.
            if len(text) < 10 or " " not in text:
                return True
            if _LOWER_WORD_RE.search(text) is None:
                return True
            return any(not (ch.isalnum() or ch in OLE_PROSE_EXTRA)
                       for ch in text)
        odd = sum(1 for ch in text
                  if not (ch.isalnum() or ch in OLE_PROSE_EXTRA))
        return (odd / max(1, len(text))) > 0.15
    except Exception:
        logger.debug("ole garbage check failed; keeping piece", exc_info=True)
        return False
